apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mi6etntxf-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:e63ad642bae5b9e277620a87d4cf0b9d5a706ca0@sha256:dfe3f966c36549c493d20bb4a3b694f7d0fa501488fced6fb02c7fabdd28a933
          name: container-image
